web:
  build: .
  command: bin/web
  environment:
    - DEVELOPMENT=true
    - MESSAGE
  ports:
    - 80:3000
    - 443:3000
  volumes:
    - .:/go/src/github.com/convox/demo
worker:
  build: .
  command: bin/work
  environment:
    - WORKER_ROLE=indexer
